[[redirects]]
  from = "/api/*"
  to = "https://azzy-issues-app-json-server.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[build]
  command = "CI= npm run build"